import { EnvironmentProviders, importProvidersFrom } from '@angular/core';
import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  MenuOutline,
  FormOutline,
  DashboardOutline,
  DashboardFill,
  SaveOutline,
  PlusOutline,
  DeleteOutline,
  EditOutline,
  ArrowRightOutline,
  MessageOutline,
  DownOutline,
  UserOutline,
  TeamOutline,
  SafetyOutline,
  IdcardOutline,
  LockOutline,
  LockFill,
  SettingOutline,
  SettingFill,
  ApartmentOutline,
  SearchOutline,
  ReloadOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  ClockCircleOutline,
  ExclamationCircleOutline,
  InfoCircleOutline,
  QuestionCircleOutline,
  UpOutline,
  LeftOutline,
  RightOutline,
  FilterOutline,
  EyeOutline,
  EyeInvisibleOutline,
} from '@ant-design/icons-angular/icons';
import { NzIconModule } from 'ng-zorro-antd/icon';

const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  MenuOutline,
  DashboardOutline,
  DashboardFill,
  FormOutline,
  SaveOutline,
  PlusOutline,
  DeleteOutline,
  EditOutline,
  ArrowRightOutline,
  MessageOutline,
  DownOutline,
  UpOutline,
  LeftOutline,
  RightOutline,
  UserOutline,
  TeamOutline,
  SafetyOutline,
  IdcardOutline,
  LockOutline,
  LockFill,
  SettingOutline,
  SettingFill,
  ApartmentOutline,
  SearchOutline,
  ReloadOutline,
  CloseCircleOutline,
  CheckCircleOutline,
  ClockCircleOutline,
  ExclamationCircleOutline,
  InfoCircleOutline,
  QuestionCircleOutline,
  FilterOutline,
  EyeOutline,
  EyeInvisibleOutline,
];

export function provideNzIcons(): EnvironmentProviders {
  return importProvidersFrom(NzIconModule.forRoot(icons));
}
